# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modisTrack_main_ui.ui'
#
# Created: Mon Jan 18 03:51:53 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(468, 460)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/modisTrackL1L2/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.objectsGroupBox = QtGui.QGroupBox(Dialog)
        self.objectsGroupBox.setObjectName(_fromUtf8("objectsGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.objectsGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.closeButton = QtGui.QPushButton(self.objectsGroupBox)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.runButton = QtGui.QPushButton(self.objectsGroupBox)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout_2.addWidget(self.runButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.checkoutForObjectsCheckBox = QtGui.QCheckBox(self.objectsGroupBox)
        self.checkoutForObjectsCheckBox.setObjectName(_fromUtf8("checkoutForObjectsCheckBox"))
        self.gridLayout_3.addWidget(self.checkoutForObjectsCheckBox, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.objectsGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.checkoutTextBox = QtGui.QTextBrowser(self.objectsGroupBox)
        self.checkoutTextBox.setEnabled(True)
        self.checkoutTextBox.setObjectName(_fromUtf8("checkoutTextBox"))
        self.gridLayout_3.addWidget(self.checkoutTextBox, 3, 0, 1, 1)
        self.layersComboBox = QtGui.QComboBox(self.objectsGroupBox)
        self.layersComboBox.setEnabled(False)
        self.layersComboBox.setObjectName(_fromUtf8("layersComboBox"))
        self.gridLayout_3.addWidget(self.layersComboBox, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.objectsGroupBox)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 5, 0, 1, 1)
        self.gridLayout_5.addWidget(self.objectsGroupBox, 0, 1, 3, 1)
        self.orbitGroupBox = QtGui.QGroupBox(Dialog)
        self.orbitGroupBox.setObjectName(_fromUtf8("orbitGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.orbitGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.orbitGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.orbitGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.orbitDate = QtGui.QDateEdit(self.orbitGroupBox)
        self.orbitDate.setCalendarPopup(True)
        self.orbitDate.setObjectName(_fromUtf8("orbitDate"))
        self.gridLayout.addWidget(self.orbitDate, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.orbitGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.TLELine2 = QtGui.QLineEdit(self.orbitGroupBox)
        self.TLELine2.setObjectName(_fromUtf8("TLELine2"))
        self.gridLayout.addWidget(self.TLELine2, 3, 1, 1, 1)
        self.HelpLabel = QtGui.QLabel(self.orbitGroupBox)
        self.HelpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HelpLabel.setOpenExternalLinks(True)
        self.HelpLabel.setObjectName(_fromUtf8("HelpLabel"))
        self.gridLayout.addWidget(self.HelpLabel, 4, 0, 1, 1)
        self.TLELine1 = QtGui.QLineEdit(self.orbitGroupBox)
        self.TLELine1.setObjectName(_fromUtf8("TLELine1"))
        self.gridLayout.addWidget(self.TLELine1, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.autoTLEButton = QtGui.QPushButton(self.orbitGroupBox)
        self.autoTLEButton.setObjectName(_fromUtf8("autoTLEButton"))
        self.horizontalLayout.addWidget(self.autoTLEButton)
        self.TLESettingsButton = QtGui.QPushButton(self.orbitGroupBox)
        self.TLESettingsButton.setObjectName(_fromUtf8("TLESettingsButton"))
        self.horizontalLayout.addWidget(self.TLESettingsButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.orbitGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.satelliteComboBox = QtGui.QComboBox(self.orbitGroupBox)
        self.satelliteComboBox.setObjectName(_fromUtf8("satelliteComboBox"))
        self.satelliteComboBox.addItem(_fromUtf8(""))
        self.satelliteComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.satelliteComboBox, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.orbitGroupBox, 0, 0, 1, 1)
        self.outputsGroupBox = QtGui.QGroupBox(Dialog)
        self.outputsGroupBox.setObjectName(_fromUtf8("outputsGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.outputsGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.addOutputsToProjectCheckBox = QtGui.QCheckBox(self.outputsGroupBox)
        self.addOutputsToProjectCheckBox.setObjectName(_fromUtf8("addOutputsToProjectCheckBox"))
        self.gridLayout_2.addWidget(self.addOutputsToProjectCheckBox, 5, 0, 1, 1)
        self.extentPolygonsOutputLine = QtGui.QLineEdit(self.outputsGroupBox)
        self.extentPolygonsOutputLine.setReadOnly(True)
        self.extentPolygonsOutputLine.setObjectName(_fromUtf8("extentPolygonsOutputLine"))
        self.gridLayout_2.addWidget(self.extentPolygonsOutputLine, 3, 0, 1, 1)
        self.extentPolygonsOutputBrowseButton = QtGui.QPushButton(self.outputsGroupBox)
        self.extentPolygonsOutputBrowseButton.setObjectName(_fromUtf8("extentPolygonsOutputBrowseButton"))
        self.gridLayout_2.addWidget(self.extentPolygonsOutputBrowseButton, 3, 1, 1, 1)
        self.satellitePositionOutputCheckBox = QtGui.QCheckBox(self.outputsGroupBox)
        self.satellitePositionOutputCheckBox.setChecked(True)
        self.satellitePositionOutputCheckBox.setObjectName(_fromUtf8("satellitePositionOutputCheckBox"))
        self.gridLayout_2.addWidget(self.satellitePositionOutputCheckBox, 0, 0, 1, 1)
        self.satellitePositionOutputLine = QtGui.QLineEdit(self.outputsGroupBox)
        self.satellitePositionOutputLine.setReadOnly(True)
        self.satellitePositionOutputLine.setObjectName(_fromUtf8("satellitePositionOutputLine"))
        self.gridLayout_2.addWidget(self.satellitePositionOutputLine, 1, 0, 1, 1)
        self.satellitePositionOutputBrowseButton = QtGui.QPushButton(self.outputsGroupBox)
        self.satellitePositionOutputBrowseButton.setObjectName(_fromUtf8("satellitePositionOutputBrowseButton"))
        self.gridLayout_2.addWidget(self.satellitePositionOutputBrowseButton, 1, 1, 1, 1)
        self.extentPolygonsOutputCheckBox = QtGui.QCheckBox(self.outputsGroupBox)
        self.extentPolygonsOutputCheckBox.setChecked(True)
        self.extentPolygonsOutputCheckBox.setObjectName(_fromUtf8("extentPolygonsOutputCheckBox"))
        self.gridLayout_2.addWidget(self.extentPolygonsOutputCheckBox, 2, 0, 1, 1)
        self.splitToMultuGeomCheckBox = QtGui.QCheckBox(self.outputsGroupBox)
        self.splitToMultuGeomCheckBox.setChecked(True)
        self.splitToMultuGeomCheckBox.setObjectName(_fromUtf8("splitToMultuGeomCheckBox"))
        self.gridLayout_2.addWidget(self.splitToMultuGeomCheckBox, 4, 0, 1, 2)
        self.gridLayout_5.addWidget(self.outputsGroupBox, 1, 0, 1, 1)
        self.ftpGroupBox = QtGui.QGroupBox(Dialog)
        self.ftpGroupBox.setObjectName(_fromUtf8("ftpGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.ftpGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.MODISProductComboBox = QtGui.QComboBox(self.ftpGroupBox)
        self.MODISProductComboBox.setObjectName(_fromUtf8("MODISProductComboBox"))
        self.gridLayout_4.addWidget(self.MODISProductComboBox, 0, 1, 1, 1)
        self.MODISGeorefLinkLabel = QtGui.QLabel(self.ftpGroupBox)
        self.MODISGeorefLinkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MODISGeorefLinkLabel.setOpenExternalLinks(True)
        self.MODISGeorefLinkLabel.setObjectName(_fromUtf8("MODISGeorefLinkLabel"))
        self.gridLayout_4.addWidget(self.MODISGeorefLinkLabel, 2, 0, 1, 2)
        self.MODISProductLinkLabel = QtGui.QLabel(self.ftpGroupBox)
        self.MODISProductLinkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MODISProductLinkLabel.setOpenExternalLinks(True)
        self.MODISProductLinkLabel.setObjectName(_fromUtf8("MODISProductLinkLabel"))
        self.gridLayout_4.addWidget(self.MODISProductLinkLabel, 1, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.ftpGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.ftpGroupBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "MODIS Track L1L2", None))
        self.objectsGroupBox.setTitle(_translate("Dialog", "Check out scenes for objects", None))
        self.closeButton.setText(_translate("Dialog", "Close", None))
        self.runButton.setText(_translate("Dialog", "Run", None))
        self.checkoutForObjectsCheckBox.setText(_translate("Dialog", "Objects from layer:", None))
        self.label_5.setText(_translate("Dialog", "Output:", None))
        self.checkoutTextBox.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.orbitGroupBox.setTitle(_translate("Dialog", "Orbit settings", None))
        self.label_2.setText(_translate("Dialog", "TLE line 1", None))
        self.label.setText(_translate("Dialog", "Date", None))
        self.label_3.setText(_translate("Dialog", "TLE line 2", None))
        self.HelpLabel.setText(_translate("Dialog", "<a href=\"ekazakov.info\">Help</a>", None))
        self.autoTLEButton.setText(_translate("Dialog", "Auto", None))
        self.TLESettingsButton.setText(_translate("Dialog", "Settings", None))
        self.label_4.setText(_translate("Dialog", "Satellite", None))
        self.satelliteComboBox.setItemText(0, _translate("Dialog", "Terra", None))
        self.satelliteComboBox.setItemText(1, _translate("Dialog", "Aqua", None))
        self.outputsGroupBox.setTitle(_translate("Dialog", "Outputs", None))
        self.addOutputsToProjectCheckBox.setText(_translate("Dialog", "Add to project", None))
        self.extentPolygonsOutputBrowseButton.setText(_translate("Dialog", "...", None))
        self.satellitePositionOutputCheckBox.setText(_translate("Dialog", "Satellite position track", None))
        self.satellitePositionOutputBrowseButton.setText(_translate("Dialog", "...", None))
        self.extentPolygonsOutputCheckBox.setText(_translate("Dialog", "Scene\'s extent polygons", None))
        self.splitToMultuGeomCheckBox.setText(_translate("Dialog", "Split scenes around lon ±180 to multigeometry", None))
        self.ftpGroupBox.setTitle(_translate("Dialog", "NASA FTP Link", None))
        self.MODISGeorefLinkLabel.setText(_translate("Dialog", "<a href = \"...\">Georeferencing files link</a>", None))
        self.MODISProductLinkLabel.setText(_translate("Dialog", "<a href = \"...\">Product link</a>", None))
        self.label_6.setText(_translate("Dialog", "Product", None))
